### ISSUE TITLE
RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'

### ISSUE THREAD

**Issue by mzamini92** [ziangcao0312/DiffTF#3]
Hi. I was trying to run the code. I couldnt run with the format you mentioned. but other than that, when I use the following command instead, I dont know why when I am trying to train on 2 GPUs on a Lambda machine I get these errors!
I ran this code:
```
torchrun --nproc_per_node 2 ./Triplanerecon/train.py --config ./Triplanerecon/configs/omni/train.txt --datadir ./dataset/Omniobject3D/renders --basedir ./Checkpoint --expname omni_sharedecoder
```
I got these errors"
```
1
1
error state
error state
Not ndc!
Not ndc!
[2024-02-08 21:55:56,919][train.py][line:69][INFO] start training!
[2024-02-08 21:55:56,919][train.py][line:69][INFO] start training!
Traceback (most recent call last):
  File "/data/class/OmniObject3D/DiffTF/./Triplanerecon/train.py", line 163, in <module>
    train(args)
  File "/data/class/OmniObject3D/DiffTF/./Triplanerecon/train.py", line 76, in train
    for data in training_loader:
  File "/home/ssl/miniconda3/envs/difftf/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/ssl/miniconda3/envs/difftf/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 673, in _next_data
    index = self._next_index()  # may raise StopIteration
  File "/home/ssl/miniconda3/envs/difftf/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 620, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/ssl/miniconda3/envs/difftf/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 283, in __iter__
    for idx in self.sampler:
  File "/home/ssl/miniconda3/envs/difftf/lib/python3.10/site-packages/torch/utils/data/distributed.py", line 101, in __iter__
    indices = torch.randperm(len(self.dataset), generator=g).tolist()  # type: ignore[arg-type]
RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'
Traceback (most recent call last):
  File "/data/class/OmniObject3D/DiffTF/./Triplanerecon/train.py", line 163, in <module>
    train(args)
  File "/data/class/OmniObject3D/DiffTF/./Triplanerecon/train.py", line 76, in train
    for data in training_loader:
  File "/home/ssl/miniconda3/envs/difftf/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/ssl/miniconda3/envs/difftf/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 673, in _next_data
    index = self._next_index()  # may raise StopIteration
  File "/home/ssl/miniconda3/envs/difftf/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 620, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/ssl/miniconda3/envs/difftf/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 283, in __iter__
    for idx in self.sampler:
  File "/home/ssl/miniconda3/envs/difftf/lib/python3.10/site-packages/torch/utils/data/distributed.py", line 101, in __iter__
    indices = torch.randperm(len(self.dataset), generator=g).tolist()  # type: ignore[arg-type]
RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'
[2024-02-08 21:55:59,765] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 738501) of binary: /home/ssl/miniconda3/envs/difftf/bin/python
Traceback (most recent call last):
  File "/home/ssl/miniconda3/envs/difftf/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.1.0', 'console_scripts', 'torchrun')())
  File "/home/ssl/miniconda3/envs/difftf/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/ssl/miniconda3/envs/difftf/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/ssl/miniconda3/envs/difftf/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/ssl/miniconda3/envs/difftf/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ssl/miniconda3/envs/difftf/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./Triplanerecon/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-02-08_21:55:59
  host      : SSL
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 738502)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-02-08_21:55:59
  host      : SSL
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 738501)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================


```

Any help would be appreciated!
when I also look at the train.py code I cant find `datadir` and `basedir` args.

**Comment by ziangcao0312** [comment]
This error is caused by the dataload function. As shown in the information that you provided, you can modify the /home/ssl/miniconda3/envs/difftf/lib/python3.10/site-packages/torch/utils/data/distributed.py. 

g = torch.Generator()   -->g = torch.Generator(device='cuda')
g.manual_seed(self.seed + self.epoch)
indices = torch.randperm(len(self.dataset), generator=g).tolist()
